### ISSUE TITLE
Tridents Tale GOG game - toast & chromium notifications not working

### ISSUE THREAD

**Issue by Potlu213** [darktakayanagi/Achievement-Watcher#14]
⚠️ The github issue tracker is not a piracy helpdesk 🙃
I would like to remind you that I do not endorse piracy. AW's purpose is merely educational.
They are other places to discuss _"how to make x game work"_. Unless it directly concerns AW's ability to parse achievement in this case please do speak up.

**Describe the bug**
The achievements for the game 'Tridents Tale' are not generating toast & chromium notifications. They are being recorded in AWS though.

GOG game: https://www.gogdb.org/product/1496681836#details
Galaxy64 DLL version: 1.152.1.0

**Expected behavior**

**To Reproduce**
If possible the steps to reproduce the behavior:

1. Run univeraLANserver, run the game exe
2. Generate an ach & check for notification -> toast/chromium

**Log(s)**
Logs don't lie 🙃 ! And are very useful to me.
They are located in `%AppData%\Achievement Watcher\logs`
Please do share them (in zip archive or whatever)

**Additional context / Screenshot**

[notification.log](https://github.com/user-attachments/files/24227260/notification.log)

[logs.zip](https://github.com/user-attachments/files/24227261/logs.zip)

**Comment by darktakayanagi** [comment]
@Potlu213 
fixed in https://github.com/darktakayanagi/Achievement-Watcher/releases/tag/2.0.30
please test if possible and let me know if it works for you

**Comment by Potlu213** [comment]
@darktakayanagi - i saw the release notes mention that for gog achievements, it requires a gog account. how will that work? do i need to add that somewhere? i checked the settings & i only see steam api key option but no gog option.

can you explain this please?

Update
--------
I haven't run any gog game to test but i already see 1 issue - the achievements that i had for gog games showing so far are gone. they were showing in previous version so seems something is broken in new one. about the notifications themselves, i will only be able to confirm when i play a gog game.

**Comment by darktakayanagi** [comment]
@Potlu213

> [@darktakayanagi](https://github.com/darktakayanagi) - i saw the release notes mention that for gog achievements, it requires a gog account. how will that work? do i need to add that somewhere? i checked the settings & i only see steam api key option but no gog option.
> 
> can you explain this please?

sure,
gog doesn't use an api key like steam, in fact, it doesn't even have public api endpoints for people to get data from. both the website and the gog galaxy client use an access token as authentication to get the data it needs, (more info [here](https://gogapidocs.readthedocs.io/en/latest/auth.html#introduction))
when AW tries to get gog data, it will open a browser window to the gog website for you to log in, when you do, it saves the token locally to be used to query the data. (AW doesn't have access to the password nor does it save the credentials anywhere, the token is used just as a sort of identifier)
you only have to log in once, the token can be reused indefinitely to fetch data (if the token expires, it refreshes itself without need for user input)
being a token and not an api key, it does give AW the possibility to do more stuff than just getting game data,
and while AW doesn't do anything except get game data (the source code for this will be posted later), in theory the token can be used to accept/decline/block friends, add/remove stuff from cart, and change a few things like avatar, default currency, etc (it cant change the password tho)
for the paranoid people, a throwaway account can be used to log in when AW asks for it (its not required to have any games or anything like that).
the reason i didn't use a throwaway account for everyone as the default and included it on the installer is to not break GOG's ToS.

all this can be disabled, i haven't added an visual option on the settings yet but the `options.ini` file has an entry there that can be switched to 'false' to disable the use of the token.
if disabled, data will be fetched from steam like before (gog exclusives wont be supported and mismatches in achievements between `steam <-> gog` will also be unsupported)


> ## Update
> I haven't run any gog game to test but i already see 1 issue - the achievements that i had for gog games showing so far are gone. they were showing in previous version so seems something is broken in new one. about the notifications themselves, i will only be able to confirm when i play a gog game.

that is correct, i had a typo on the code and it was skipping the gog part, thats why gog games stopped showing and why it didnt show the login page.
2.0.31 will be released today to fix this.

**Comment by Potlu213** [comment]
unfortunately, gog games are still not showing in 2.0.31. 

[logs-2031.zip](https://github.com/user-attachments/files/24632349/logs-2031.zip)

**Comment by darktakayanagi** [comment]
@Potlu213
they aren't showing on the gamelist?
it is working on my end, and the logs dont show anything wrong.
I'll add some some more info to the logs on 3.0.32 to helps us troubleshoot this.

in the meantime, could you remove the paths on the userdir settings for the gog games and add them back again to see if this fixes it?
Also, can you start a gog game and close it then send the logs?

**Comment by Potlu213** [comment]
@darktakayanagi - i tried removing & adding the folders for the games but that did not work.
so finally i installed 1 of the games - Tridents Tale & it asked me to login to GOG which i did.
post that, when i opened AW, the game still did not show up. i removed the folder for the game & added it back again & finally it did show up but there is an issue. it is showing all achievements as unlocked even though some of them were not unlocked by me.

so i see 2 issues:
1. getting achievements for games already played to show will require the user to install them back, start & then remove/add folder back.
2. achievements unlocked is broken - it should only show those unlocked which i actually did.

attached the logs from AW & the achievements.ini file from the game which shows 19/24 achieved.

[logs-gog.zip](https://github.com/user-attachments/files/24647229/logs-gog.zip)
